export * from './series/series.component';
export * from './series/series.route';
export * from './series-add/series-add.component';
export * from './series-update/series-update.component';
export * from './aif2-series-master/aif2-series-master/aif2-series-master.component';
export * from './aif2-series-master/aif2-series-master-add/aif2-series-master-add.component';
export * from './aif2-series-master/aif2-series-master-update/aif2-series-master-update.component';
export * from './aif2-series-master/aif2-series-master.service';
export * from './series.route';
